version: 2

defaults: &defaults
  working_directory: ~/urbanmassage
  docker:
    - image: circleci/node:10

jobs:
  build:
    <<: *defaults  
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: |
            npm i
            npm prune
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Test
          command: npm test
      - persist_to_workspace:
          root: ~/urbanmassage
          paths: .
  release:
    <<: *defaults  
    steps:
      - attach_workspace:
          at: ~/urbanmassage
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/urbanmassage/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/